name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use OCaml 5.0.0+custom-events
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.5.0.0+custom-events
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            custom-events: https://github.com/TheLortex/custom-events-opam-repository.git

      - name: Meio Deps 🐈‍⬛
        run: opam pin . -yn && opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Update asciicast dependencies
        run: |
          go install github.com/christopher-dG/asciiscript@latest
          sudo apt install asciinema

      - name: Run asciicast
        shell: 'script --return --quiet --command "bash {0}"'
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          export TERM=xterm-256color
          stty rows 40 cols 160
          asciiscript .screencast/example.sh .screencast/example.cast --overwrite

      - uses: actions/upload-artifact@v3
        with:
          name: asciicast
          path: .screencast/example.cast
